PayCloud.WebApp/Areas/Admin/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PayCloud.Data.DbContext;
using PayCloud.Data.Models;
using PayCloud.Services.Contracts;
using PayCloud.Services.Providers;
using PayCloud.WebApp.Areas.Admin.Models.BannerViewModels;
using PayCloud.WebApp.Mappers;
using PayCloud.WebApp.Utils;

namespace PayCloud.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [JWTAuthorizeAttribute("Admin")]

    public class BannersController : Controller
    {
        private readonly IViewModelMapper<IReadOnlyCollection<Banner>, BannersCollectionViewModel> bannersCollectionMapper;
        private readonly IViewModelMapper<Banner, BannerViewModel> bannerMapper;
        private readonly IBannerServices bannerServices;
        private readonly IFileServicesProvider fileServicesProvider;
        private readonly IDateTimeNowProvider dateTimeNowProvider;
        private readonly ILogger<BannersController> logger;

        public BannersController(
            IViewModelMapper<IReadOnlyCollection<Banner>, BannersCollectionViewModel> bannersCollectionMapper,
            IViewModelMapper<Banner, BannerViewModel> bannerMapper,
            IBannerServices bannerServices,
            IFileServicesProvider fileServicesProvider,
            IDateTimeNowProvider dateTimeNowProvider,
            ILogger<BannersController> logger)
        {
            this.bannersCollectionMapper = bannersCollectionMapper ?? throw new ArgumentNullException(nameof(bannersCollectionMapper));
            this.bannerMapper = bannerMapper ?? throw new ArgumentNullException(nameof(bannerMapper));
            this.bannerServices = bannerServices ?? throw new ArgumentNullException(nameof(bannerServices));
            this.fileServicesProvider = fileServicesProvider ?? throw new ArgumentNullException(nameof(fileServicesProvider));
            this.dateTimeNowProvider = dateTimeNowProvider ?? throw new ArgumentNullException(nameof(dateTimeNowProvider));
            this.logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        // GET: Products list JSON for AJAX
        public async Task<IActionResult> GetBannersList(string term, int bannerTypeSelector, int? pageNumber, int? totalPages, int? pageSize)
        {
            string sortOrder = "";
            string currentFilter = "";
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["LengthOptions"] = new int[] { 5, 10, 15, 20 };

            this.ViewData["CurrentFilter"] = currentFilter;
            //this.ViewData["ClientId"] = clientId;

            this.ViewData["pageSize"] = pageSize;

            var tmpDateTime = this.dateTimeNowProvider.Now;
            var tmpStartDateTime = new DateTime(
                tmpDateTime.Year,
                tmpDateTime.Month,
                tmpDateTime.Day,
                tmpDateTime.Hour,
                tmpDateTime.Minute,
                0, 0);
            var tmpEndDateTime = tmpStartDateTime
                .AddHours(24)
                .AddMinutes(60 - tmpStartDateTime.Minute);
            var banner = new Banner()
            {
                UrlLink = "",
                ImgLocationPath = "",
                StartDate = tmpStartDateTime,
                EndDate = tmpEndDateTime
            };
            var x = this.bannerMapper.MapFrom(banner);
            var BannerIndexViewModelObject = new BannerIndexViewModel()
            {
                BannerViewModelObject = x,
                PageIndex = pageNumber ?? 1,
                TotalPages = totalPages ?? 1,
                HasNextPage = false,
                HasPreviousPage = false,
                ElementsPerPage = pageSize ?? 5,
                ImageMaxSize = 32 * 1024,
                BannerActivityType = bannerTypeSelector,
                SearchString = term,
                AllDatabaseBannersCount = 0,
                BannersList = null
            };
            switch (BannerIndexViewModelObject.BannerActivityType)
            {
                case 1:
                    {
                        (List<Banner> filteredList, int allCount, int pageNum, int elementsPerPage) = await this.bannerServices.GetPagedAllActiveBannersByFilterAsync(
                            BannerIndexViewModelObject.PageIndex,
                            BannerIndexViewModelObject.ElementsPerPage,
                            BannerIndexViewModelObject.SearchString);
                        BannerIndexViewModelObject.BannersList = this.bannersCollectionMapper.MapFrom(filteredList);
                        BannerIndexViewModelObject.AllDatabaseBannersCount = allCount;
                        BannerIndexViewModelObject.TotalPages = (BannerIndexViewModelObject.AllDatabaseBannersCount + BannerIndexViewModelObject.ElementsPerPage - 1) / BannerIndexViewModelObject.ElementsPerPage;
                        break;
                    }
                case 2:
                    {
                        (List<Banner> filteredList, int allCount, int pageNum, int elementsPerPage) = await this.bannerServices.GetPagedAllInactiveBannersByFilterAsync(
                            BannerIndexViewModelObject.PageIndex,
                            BannerIndexViewModelObject.ElementsPerPage,
                            BannerIndexViewModelObject.SearchString);
                        BannerIndexViewModelObject.BannersList = this.bannersCollectionMapper.MapFrom(filteredList);
                        BannerIndexViewModelObject.AllDatabaseBannersCount = allCount;
                        BannerIndexViewModelObject.TotalPages = (BannerIndexViewModelObject.AllDatabaseBannersCount + BannerIndexViewModelObject.ElementsPerPage - 1) / BannerIndexViewModelObject.ElementsPerPage;
                        break;
                    }
                case 0:
                default:
                    {
                        BannerIndexViewModelObject.BannerActivityType = 0;
                        (List<Banner> filteredList, int allCount, int pageNum, int elementsPerPage) = await this.bannerServices.GetPagedAllBannersByFilterAsync(
                            BannerIndexViewModelObject.PageIndex - 1,
                            BannerIndexViewModelObject.ElementsPerPage,
                            BannerIndexViewModelObject.SearchString);
                        BannerIndexViewModelObject.BannersList = this.bannersCollectionMapper.MapFrom(filteredList);
                        BannerIndexViewModelObject.AllDatabaseBannersCount = allCount;
                        BannerIndexViewModelObject.TotalPages = (BannerIndexViewModelObject.AllDatabaseBannersCount + BannerIndexViewModelObject.ElementsPerPage - 1) / BannerIndexViewModelObject.ElementsPerPage;
                        break;
                    }
            }
            if ((BannerIndexViewModelObject.PageIndex * BannerIndexViewModelObject.ElementsPerPage) > BannerIndexViewModelObject.AllDatabaseBannersCount)
            {
                if (BannerIndexViewModelObject.AllDatabaseBannersCount < BannerIndexViewModelObject.ElementsPerPage)
                {
                    //BannerIndexViewModelObject.PageIndex = 1;
                }
                else
                {
                    //BannerIndexViewModelObject.PageIndex = BannerIndexViewModelObject.AllDatabaseBannersCount / BannerIndexViewModelObject.ElementsPerPage;
                }
            }
            BannerIndexViewModelObject.HasPreviousPage = (BannerIndexViewModelObject.PageIndex > 1) ? true : false;
            BannerIndexViewModelObject.HasNextPage = (BannerIndexViewModelObject.PageIndex < BannerIndexViewModelObject.TotalPages) ? true : false;
            var result1 = PaginatedList<BannerViewModel>.Create(BannerIndexViewModelObject.BannersList.Banners.ToList(), BannerIndexViewModelObject.AllDatabaseBannersCount/*accountsCount*/, BannerIndexViewModelObject.PageIndex, BannerIndexViewModelObject.ElementsPerPage/*(int)pageSize*/, true);
            return this.PartialView("_BannersListPartial", result1);
            //return this.Json(new  BannerIndexViewModelObject);
        }

        // GET: Admin/Banners
        [HttpGet]
        public async Task<IActionResult> Index(int? pageNumber, int? totalPages, int? pageSize)
        {
            this.ViewData["Title"] = "Banners administration";
            var tmpDateTime = this.dateTimeNowProvider.Now;
            var tmpStartDateTime = new DateTime(
                tmpDateTime.Year,
                tmpDateTime.Month,
                tmpDateTime.Day,
                tmpDateTime.Hour,
                tmpDateTime.Minute,
                0, 0);
            var tmpEndDateTime = tmpStartDateTime
                .AddHours(24)
                .AddMinutes(60 - tmpStartDateTime.Minute);
            var banner = new Banner()
            {
                UrlLink = "",
                ImgLocationPath = "",
                StartDate = tmpStartDateTime,
                EndDate = tmpEndDateTime
            };
            var x = this.bannerMapper.MapFrom(banner);
            var BannerIndexViewModelObject = new BannerIndexViewModel()
            {
                BannerViewModelObject = x,
                PageIndex = pageNumber??1,
                TotalPages = totalPages??1,
                HasNextPage = false,
                HasPreviousPage = false,
                ElementsPerPage = pageSize??5,
                ImageMaxSize = 32 * 1024,
                BannerActivityType = 0,
                SearchString = "",
                AllDatabaseBannersCount = 0,
                BannersList = null
            };
            (List<Banner> filteredList, int allCount, int pageNumberTmp, int elementsPerPage) = await this.bannerServices.GetPagedAllBannersByFilterAsync(

PayCloud.WebApp/Areas/Admin/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using PayCloud.Services;
using PayCloud.Services.Dto;
using PayCloud.WebApp.Utils;
using System;
using System.Threading.Tasks;

namespace PayCloud.WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [JWTAuthorizeAttribute("Admin")]

    public class ClientsController : Controller
    {
        private readonly IClientService clientService;

        // GET: Admin/Clients
        public async Task<IActionResult> Index(bool clientSelect=true)
        {
            this.ViewData["Title"] = "Clients management page";
            return this.View(clientSelect);
        }

        public ClientsController(IClientService clientService)
        {
            this.clientService = clientService ?? throw new ArgumentNullException(nameof(clientService));
        }

        // GET: Products list JSON for AJAX
        public async Task<IActionResult> ClientList(string term)
        {
            return this.Json(await this.clientService.GetClientsListAsync(0, 10, term:term));
        }

        // POST: Admin/Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody]string clientName)
        {
            try
            {
                var newClient = await this.clientService.CreateClientAsync(clientName);
                return this.Json(string.Format(Constants.ClientCreated, clientName));
            }
            catch (Exception ex)
            {
                return this.BadRequest(this.Json(ex.Message));
            }
        }

        public async Task<IActionResult> GetClientsList(
                   string sortOrder,
                   string currentFilter,
                   int? pageNumber,
                   int? pageSize)
        {
            this.ViewData["ClientIdSortParm"] = (string.IsNullOrEmpty(sortOrder) || sortOrder=="ClientId") ? "ClientId_desc" : "ClientId";
            this.ViewData["ClientNameSortParm"] = sortOrder == "Name" ? "Name_desc" : "Name";
            this.ViewData["CurrentSort"] = sortOrder;
            this.ViewData["LengthOptions"] = new int[] { 5, 10, 15, 20 };

            this.ViewData["CurrentFilter"] = currentFilter;

            if (pageSize == null)
            {
                pageSize = 5;
            }
            this.ViewData["pageSize"] = pageSize;

            var pageIndex = pageNumber ?? 1;

            var clients = await this.clientService.GetClientsListAsync((pageIndex - 1) * (int)pageSize, (int)pageSize, currentFilter, sortOrder: sortOrder);
            var clientsCount = await this.clientService.GetClientsCountAsync(currentFilter);

            var result = PaginatedList<ClientDto>.Create(clients, clientsCount, pageIndex, (int)pageSize, true);

            return this.PartialView("_ClientsListPartial", result);
        }
    }
}

PayCloud.WebApp/Areas/User/Controllers/IdentityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PayCloud.Services.Identity.Contracts;
using PayCloud.WebApp.Models;
using System;
using System.Threading.Tasks;

namespace PayCloud.WebApp.Areas.User.Controllers
{
    [Area("User")]
    public class IdentityController : Controller
    {
        private readonly ITokenManager tokenManager;
        private readonly IUserService userService;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ICookieManager cookieManager;

        public IdentityController(
            IUserService userService,
            ITokenManager tokenManager,
            IHttpContextAccessor httpContextAccessor,
            ICookieManager cookieManager)
        {
            this.userService = userService;
            this.tokenManager = tokenManager;
            this.httpContextAccessor = httpContextAccessor;
            this.cookieManager = cookieManager;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel userModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(userModel);
                }

                var user = await userService.GetUserAsync(userModel.Username, userModel.Password);

                var token = tokenManager.GenerateToken(user.Username, user.Role, user.UserId.ToString());

                cookieManager.AddSessionCookieForToken(token, user.Username);

                if (user.Role == "User")
                {
                    return RedirectToAction("Index", "Accounts", new { area = "User" });
                }
                else
                {
                    return RedirectToAction("AdminLogin");

                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home", new { errorMessage = ex.Message });

                //return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            try
            {
                cookieManager.DeleteSessionCookies();
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

PayCloud.WebApp/Areas/Admin/Views/Shared/_AccountBoxesPartial.cshtml
<div class="row">

    <div class="col-xl-4 col-sm-6">
        <div class="card mb-4">
            <div class="card-sm-header">
                <span class="wallet-heading"><i class="cc BTC text_primary" title="BTC"></i><h4>Bitcoin</h4></span>
            </div>
            <div class="card-body">
                <ul class="list_none p-0 wallet_info">
                    <li>
                        <span>Available</span>
                        <span>2.25142 BTC</span>
                    </li>
                    <li>
                        <span>Total Sell</span>
                        <span>$2565.55</span>
                    </li>
                    <li>
                        <span>Total Buy</span>
                        <span>$2352.80</span>
                    </li>
                </ul>
                <a href="#" class="btn btn-primary">Withdraw</a>
                <a href="#" class="btn btn-dark">Diposit</a>
            </div>
        </div>
    </div>
</div>

PayCloud.WebApp/Areas/Admin/Views/Shared/_CreateBannerPartial.cshtml
@model BannerViewModel

<hr />
<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-header">Banner Create Form</div>
            <div class="card-body">
                <div class="table-responsive">
                    <div class="dataTables_wrapper container-fluid dt-bootstrap4">
                        <div class="row">
                            <form asp-area="Admin" asp-controller="Banners" asp-action="Create" enctype="multipart/form-data">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <!-- Preview image before upload -->
                                        <p>Preview</p>
                                        <div id="wrapper" style="width:200px;height:200px">
                                            <div id="banner-image-holder"> </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div id="bannerFileformSection" class="form-group">
                                            <input id="fileUpload" asp-for="@Model.ImageData" type="file" />
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="@Model.StartDate" class="control-label"></label>
                                            <input asp-for="@Model.StartDate" class="form-control" />
                                            <span asp-validation-for="@Model.StartDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="@Model.EndDate" class="control-label"></label>
                                            <input asp-for="@Model.EndDate" class="form-control" />
                                            <span asp-validation-for="@Model.EndDate" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <input type="submit" id="createBannerPartialButtonId" value="Create" class="btn btn-primary" />
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group">
                                        <label asp-for="@Model.ImageLocationPath" class="control-label"></label>
                                        <input id="SelectedImageName" asp-for="@Model.ImageLocationPath" class="form-control" pattern=".{3,}" required placeholder="image path and name: 3 characters minimum" width="250" />
                                        <span asp-validation-for="@Model.ImageLocationPath" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="form-group">
                                        <label asp-for="@Model.UrlLink" class="control-label"></label>
                                        <input asp-for="@Model.UrlLink" class="form-control" pattern=".{3,}" required placeholder=" url link: 3 characters minimum" width="250" />
                                        <span asp-validation-for="@Model.UrlLink" class="text-danger"></span>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

PayCloud.WebApp/Areas/Admin/Views/Shared/_CreateClientPartial.cshtml

<div class="card mb-4">
    <div class="card-header">Create client</div>
    <div class="card-body">
        <form class="form-horizontal row mt-2" id="create-client-form">
            <div class="col-xl-12 col-lg-12  col-sm-12">
                <div class="form-group">
                    <label>New client name</label>
                    <input type="text" class="form-control" placeholder="Client name - 3 to 35 symbols" ID="clientName" required autofocus="">
                </div>
            </div>

            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 text-left">
            @*<p>Zakomentareno ot Vasil VNY</p>*@
            <button type="button" class="btn btn-default mt-2" onclick="ShowClientListModal();">Clients list</button>
            </div>
            @*<div class="col-6 text-left">
                <button type="button" class="btn btn-default mt-2" onclick="EditClientModal();">Edit client</button>
            </div>*@
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 text-right">
                <button type="submit" class="btn btn-default mt-2">Create</button>
            </div>
        </form>
    </div>
</div>

PayCloud.WebApp/Areas/Admin/Views/Shared/_LayoutUI.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content>
    <meta name="author" content>
    <title>@ViewData["Title"] - PayCloud.WebApp</title>
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="../assets/images/favicon.png">
    <!-- Bootstrap core CSS-->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Google Font -->
    <!-- Icon Fonts-->
    <link href="/vendor/webfont/css/cryptocoins.css" rel="stylesheet" type="text/css">
    <link href="/vendor/webfont/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="/css/admin.css" rel="stylesheet">
    <!-- Toastr-->
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">*@
    <link rel="stylesheet" href="~/css/toastr.min.css">
    <!-- JQuery UI css-->
    <link rel="stylesheet" href="~/jquery-ui-1.12.1/jquery-ui.min.css">
    <!-- Custom styles for project-->
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="fixed-nav sticky-footer" id="page-top">
    <div class="bg_image h-100">

        <span class="AntiForge"> @Html.AntiForgeryToken() </span>
        <partial name="_SideNavPartial" />
        <div class="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
        <!-- /.container-fluid-->
        <!-- /.content-wrapper-->
        <footer class="sticky-footer">
            <div class="container">
                <div class="text-center">
                    <div>
                        <img src="~/images/Email_icon.svg" alt="Email:" style="width:30px;height:30px"/>
                        <small>cloud.team.public.relations@gmail.com</small>
                    </div>
                    @*<small>Stanislav Dinev - Vasil Yoshovski</small>
                    <br />*@
                    <small>© 2019 Telerik Academy.</small>
                </div>
            </div>
        </footer>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded btn-default" onclick="window.scrollTo(0, 0);">
            <i class="fa fa-angle-up"></i>
        </a>
    </div>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Do you want to end your current session...</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href='@Url.Action("Logout","Identity")' onclick="userRemoveSessionSelect();">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script src="/vendor/chart.js/Chart.min.js"></script>
    <script src="/vendor/datatables/jquery.dataTables.js"></script>
    <script src="/vendor/datatables/dataTables.bootstrap4.js"></script>
    <!--Perfect scrollbar.js-->
    <script src="/js/perfect-scrollbar.js"></script>
    <!-- countdown js  -->
    <script src="/js/jquery.countdown.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="/js/admin.js"></script>
    <!-- Custom scripts for this page-->
    <script src="/js/admin-datatables.min.js"></script>
    @*<script src="/js/admin-charts.min.js"></script>*@
    <!-- Toastr-->
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>*@
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/toastrOptions.js"></script>

    <!-- JQuery UI-->
    <script src="~/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    <script src="~/js/userMenu.js"></script>
    @*<script src="~/js/site.js" asp-append-version="true"></script>*@

    @RenderSection("Scripts", required: false)
</body>
</html>


PayCloud.WebApp/Areas/Admin/Views/Shared/_SideNavPartial.cshtml
  <!-- Navigation UP-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="index">
        <img class="logo_icon" src="/images/logo_icon.png">
        <img class="logo" src="/images/dashboard_logo.png">
    </a>
    <div class="mobile_menu">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-menu icons"></span>
        </button>
        <a href="#/index.html" class="navbar-toggler" data-toggle="collapse" data-target="#navbarheader" aria-controls="navbarheader" aria-expanded="false" aria-label="Toggle navigation"><i class="icon-options-vertical"></i></a>
    </div>
    <div class="collapse navbar-collapse" id="navbarheader">
        <ul class="navbar-nav">
            <li class="nav-item d-none d-lg-block">
                <a class="nav-link text-center menubar" id="sidenavToggler">
                    <span class="line"></span>
                    <span class="line"></span>
                    <span class="line"></span>
                </a>
            </li>
            <li class="nav-item">
                <a href="javascript:void(0)/index.html" class="search_icon"><i class="fa fa-search"></i></a>
                <form class="form-inline search_input">
                    <div class="input-group">
                        <input class="form-control" type="text" placeholder="Search for...">
                        <span class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </li>
        </ul>
        <partial name="_UserBannerPartial">
    </div>

    <!-- Navigation SIDE-->

    <div class="collapse navbar-collapse navbar-sidenav fc-scroll" id="navbarResponsive">
        <ul class="navbar-nav" id="exampleAccordion">
            <li class="nav-item active" id="menu-item1">
                <a class="nav-link" asp-area="Admin" asp-controller="Accounts" asp-action="Index" onclick="return menuClick('menu-item1');">
                    <i class="icon-wallet icons"></i>
                    <span class="nav-link-text">User management</span>
                </a>
            </li>
            <li class="nav-item" id="menu-item2">
                <a class="nav-link" asp-area="Admin" asp-controller="Banners" asp-action="Index" onclick="return menuClick('menu-item2');">
                    <i class="icon-grid icons"></i>
                    <span class="nav-link-text">Banner management</span>
                </a>
            </li>
            @*<p>Zakomentareno ot vasil VNY</p>
        <li class="nav-item">
            <a class="nav-link" asp-area="Admin" asp-controller="Clients" asp-action="Index">
                <i class="icon-bag icons"></i>
                <span class="nav-link-text">Client management</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Admin" asp-controller="PayCloudUsers" asp-action="Index">
                <i class="icon-shuffle icons"></i>
                <span class="nav-link-text">User management</span>
            </a>
        </li>*@
            @*<li class="nav-item">
            <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages/index.html" data-parent="#exampleAccordion">
                <i class="icon-user-follow icons"></i>
                <span class="nav-link-text">My Account</span>
            </a>
            <ul class="sidenav-second-level collapse" id="collapseExamplePages">
                <li>
                    <a href="profile.html">Profile</a>
                </li>
                <li>
                    <a href="login.html">Login</a>
                </li>
                <li>
                    <a href="register.html">Registration</a>
                </li>
            </ul>
        </li>*@
        </ul>
    </div>

</nav>